language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: s/8r3o04R+Ri8rnRQsU5QOJVi3i0jkNksXkO99D/IRciSbwnqaJkCKIFhy8XJfrnJfmR+euw191jUMCQNJglXZGFxYva1Sb8qxy72bfCtutYCAQspI3JJFiy92XgyWqkOA6VpOV58S2OMMRTEismThGvGndWfxAY+RUah0EEFezPXoNY9Ni0jGkEKedngXuFUYlpt5HItqzCwiqjDCwxtbczlPYOnDpt+/ayy1zZZkp+sTOqbL2DV1cxoJeWQonrL3Rqt77+/cD6DnoVXuB0GCpJS5GAzPZ2EUgw+0ng7BpX30M4qYlVbcfdJOXYsqSEVL/hT/SpNk8HmXEu0+P/7EETzCc3DN/IHQhzafxRVX5Cyy2jTum9npSCZJ72YYT4kYIrgD5juEeLYvmhjry/xti0b9WQeonm5OcpqsqpTm0h9m0MIlIBoQFCJAUoxGON6SE+Xdotgb6RaayqnTmSgJRpJRD+1KS9gAAzK3nwI7QC02wD0q2C70cU1Op/ODaSmmmAj81WcZgihGrU906utz4n2Yo4zV5MrfujO+sZKbF9H1vVDxw0j4UJHHVN3uzqnyEfQmJnOaja3hGWlSZiJpsx6h2QPly1QlURUYrZD+BusQok0XKq0seh3yWHpMe8vlub1l7sec5EltpvZUMiZdQ5QuLdrIPe4nENb6N4djc=
  app: daily-planner-app
  on:
    repo: annasheik/daily-planner-client
