language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: BTD7+v03Gkntq/VpJyaT2mjc6mM0PWGNyFV9PEmct5i021BXY/CpR0LJz4DX4T//GBA0L+Vf+HPwKtlooJ5d+5f7xWD+LxB8ESpQwlPIvL6ZZIxQQA99/QZE4W10kd/DYjojrjP2MlVGlyUqXd669hkoBXOcMoDOjKG7xnzXAGddas0CdbDUC4c4TRsw1GtI71iLvZJJzeUZjmgIslyrTzV9RkKAQGsOvZhedkTeNwW6wCM0TCBcqdO6ybsQfw6jQeyriyAzGM+nCZWuKARpwKKWshkw5/9P9Afbz5xDswMbZXrVOjMQgN1ggZ9w4zW1ZfySm8Kxdfz1Qmgvqh9XzV+Jw3eoWdcswDw/E6waVwm6ATAg8r39GnJMX0mKYpqofLZ+Jwq/uJPmKXBjkBtnKmlD+230Dl7JQqE6kGW3djA0+EE5P+5NtReN8MgWYPXN8XbUZStxKJ8isrHxPZKY/1nDGAT9olp/hzxre6BMi1IS4HJ17fYTeROAIzO8T+r8jZuqL8Vyc6CLjDn29kEP+ybzS3mkgfGi6UMVB7g8rtkHXwce2nJ1b5L7T3JQ9jeFiFVClUkG5RyxJ5PS5RaQqrTkNkJPxUEi0+KG0QmN4IHEi+USYs0dFxb/G+/EZJJLNDzjHK7v8f6f4HnWAuLV5lrczRp2zCU7xQKaosFpAz0=
  app: daily-planner-app
  on:
    repo: annasheik/daily-planner-client
