language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: oIoSXYypoe5SY+WR6As23FiPEjo70aiQXpwsVe3GpfSeRXW07cgsrf11ukrM71MK8iKCpkJOGPyJ7GXd/7omyjodu0um4/5X/t5gKvQNst6NuTPPZwBVQHhe7mH7nIjT3PDKpURCUde6rp/rqAzWIG7f0AjprBa1+7lRM1vvrlJrHo2uy/jMKWiGyyHW0Id41SYE2Tl+h99hdGjaq8Zig4E9F3d81J+HwGCSHZUWKEmJMDzt6AjVMiG8tlYVL0Cq6xfhHCaeNymFnP1bnG0EU4qV3Z0HjWa9PBRJgRMm4FlEUfjupTl4mhLkxOiA8x3m9PNQL63IEuqXMVF2lbKV9pj7n6bx+C+AXT23QNnvoiKk0LvgzQrWatdxCGzORIpTsrIly6wzEOi5by2NJtvgdLnS3x/8874PRm9bnw0CmxF35PNj8DEh8AgLUvbJl9MBidaDyA8TCt8igMxSKdIrOosAHtt7vVPvLInP3c626zR1N6Ypd5MQ1o9ZaNzIffVxyTvHam5ozkpY1FzEadnEgctjSO3f41JbQTEqYhAgIM+cuqei1Q69EfcpQ2V0arlg8+hmR3slX2TcM/7WQGjTW8FXTB3RTZoBY/MFDgHtBaoBOlbLD4uWY6FX5CzY/q12Lbwtc39dMytARUh1brriYiMCnVmrp3/9tqySCoOzt3c=
  app: daily-planner-app
  on:
    repo: annasheik/daily-planner-client