language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Z4WmpI1iI1XVQfZumqvM0FcNMx0XgeBVcp6Yb3YyaXB3jfVwDOBstZVnJZtNsHm+64yqHoNMk0cFR3hHvny3N3jwZuZyC10khYBmdgK7A5a0SwrN1IxHGTLDg5lKivVid3wtaxhaw9qCFVddPIX+dwqU6+G4TCVAcTPIMfOfYeDNj+yRVf9eSHXGGHvhbCUiqMQSH2iu/ijfCWw95w8rOhc2G9L7KqfhNNY4TIOw0MwsQw7BrX5ZMuo8mSX0TmLBz7cXP1LSgI+xiRp2wPG0Pas8atFeqTTmPY9h4NTPIO8pnqsE3Nvdzyv6hpOGl5xNq/CIdP+6i1nkWdRRtLSHttqxjD1jVewmKOC/VqIYTVzh9FEPJgdGSbt/geEECcnPbP/utQR6+1DhgKQpSn6O4PVby7vCNkA/KjzjG05LkOuiHOw6CXBTIVrtICfR/Wbo7JsZzx1huDVda7h2Mhc7bOnnWRCTNiI+2uF+fRjfrZ9ZX7yW+Ova9uiiZZuM49EfRLZnIqrheSdovsZsapdzjUpBJCy0uuP39CXykU/ABeX0GmFzXgaqzN/1hCZnx5tej0tnsFJeB57MuxKZ0N4gIapTtbLCxzyXT9jP7aQbsbjxWr7/n5nVaAaz4K8u7I6tJwFaRPBja8qaI0hgQA34venZj4bgi2gUIQu8XrUqHnw=
  app: daily-planner-app
  on:
    repo: annasheik/daily-planner-client
